name: Add Comment to Jira Issue

on:
    push

jobs:
    add-issue-comment:
      name: Add comment to Jira issue
      runs-on: ubuntu-latest
      steps:

        - name: Login to Jira
          uses: atlassian/gajira-login@master
          env:
            JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        - name: Find Jira issue from GitHub commit message
          id: get_jira_issue
          uses: atlassian/gajira-find-issue-key@master
          with:
            from: commits

        - name: Post comment to Jira issue
          uses: atlassian/gajira-comment@master
          with:
            issue: ${{ steps.get_jira_issue.outputs.issue }}
            comment: "${{ github.event.pusher.name }} [pushed|${{ github.event.compare }}] to ${{ github.event.ref }} in ${{ github.event.repository.full_name }}"

