name: Transition Jira Issue

on:
    push

jobs:
    test-transition-issue:
      name: Transition Issue
      runs-on: ubuntu-latest
      steps:

        - name: Login to Jira
          uses: atlassian/gajira-login@master
          env:
            JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
            JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
            JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

        - name: Find Jira issue from GitHub commit message
          id: get_jira_issue
          uses: atlassian/gajira-find-issue-key@master
          with:
            from: commits

        - name: Transition Jira issue to Done
          uses: atlassian/gajira-transition@master
          with:
              issue: ${{ steps.get_jira_issue.outputs.issue }}
              transition: "Done"
              if: "endsWith(github.event.head_commit.message, 'CLOSE ISSUE')"
